--실습 1-2 테이블 생성
create table customer(
    cid varchar2(20) primary key not null,
    name varchar2(20)not null,
    hp char(13) unique,
    address varchar2(200),
    RDATE date not null
);

drop table customer;

create table product(
    pno number(4) primary key not null,
    pname varchar2(30) not null,
    stock number default 0 not null,
    price number,
    company NVARCHAR2(20) not null
);    

create table orders(
    ORD_NO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ORD_CID varchar2(20) not null,
    ORD_PNO number(4) not null,
    ORD_CNT number default 1 not null,
    ORD_DATE DATE not null
);    

--1-3 실습 데이터 입력
insert into customer values ('c101','김유신','010-1234-1001','김해시 봉황동','2022-01-01');
insert into customer values ('c102','김춘추','010-1234-1002','경주시 보문동','2022-01-02');
insert into customer values ('c103','장보고','010-1234-1003','완도군 청산면','2022-01-03');
insert into customer values ('c104','강감찬','010-1234-1004','서울시 마포구','2022-01-04');
insert into customer values ('c105','이성계','','','2022-01-05');
insert into customer values ('c106','정철','010-1234-1006','김해시 봉황동','2022-01-06');
insert into customer values ('c107','허준','','','2022-01-07');
insert into customer values ('c108','이순신','010-1234-1008','서울시 영등포구','2022-01-08');
insert into customer values ('c109','송상현','010-1234-1009','부산시 동래구','2022-01-09');
insert into customer values ('c110','정약용','010-1234-1010','경기도 광주시','2022-01-10');

select * from customer;

insert into product values ('1','새우깡','5000','1500','농심');
insert into product values ('2','초코파이','2500','2500','오리온');
insert into product values ('3','포카칩','3600','1700','오리온');
insert into product values ('4','양파링','1250','1800','농심');
insert into product values ('5','조리퐁','2200','','크라운');
insert into product values ('6','마가렛트','3500','3500','롯데');
insert into product values ('7','뿌셔뿌셔','1650','1200','오뚜기');

select * from product;

INSERT INTO orders (ORD_NO, ORD_CID, ORD_PNO, ORD_CNT, ORD_DATE)
VALUES (1, 'c102', 3, 2, TO_DATE('2022-07-01 13:15:10', 'YYYY-MM-DD HH24:MI:SS'));

insert into orders values('1','c102','3','2','2022-07-01 13:15:10');
insert into orders values('2','c101','4','1','2022-07-01 14:16:11');
insert into orders values('3','c108','1','1','2022-07-01 17:23:18');
insert into orders values('4','c109','6','5','2022-07-01 10:46:36');
insert into orders values('5','c102','2','1','2022-07-01 09:15:37');
insert into orders values('6','c101','7','3','2022-07-01 12:35:12');
insert into orders values('7','c110','1','2','2022-07-01 16:55:36');
insert into orders values('8','c104','2','4','2022-07-01 14:23:23');
insert into orders values('9','c102','1','3','2022-07-01 21:54:34');
insert into orders values('10','c107','6','1','2022-07-01 14:21:03');

select * from orders;

--1-4,5 실습 속성 조회
--4
select * from customer;
--5
select cid,name, hp from customer;
--6
select * from product;
--7
select company from product;
--8
select distinct company from product;
--9
select pname,price from product;
--10
select pname , price+500 as 조정단가 from product;
--11
select pname, stock, price from product where company = '오리온';
--12
select ORD_PNO,ORD_CNT,ORD_DATE from orders where ORD_CID = 'c102';
--13
select * from product where price >= 1000 and price<=2000;
--14
select cid,name,hp,address from customer where name like '김%' ;
--15
select cid, name, hp, address from customer where length(name)=2;
select cid, name, hp, address from customer where name like '__';
--16
select * from customer where hp is null or hp = '';
--17
select * from customer where address is not null;
--18
select * from customer order by rdate desc;
--19
select * from orders where ORD_CNT >= 3 order by ORD_CNT desc,ORD_PNO asc;
--20
select avg(price) from product;
--21
select sum(stock) as "재고량합계" from product where company='농심';
--22
select count(*) as 고객수 from customer;
--23
select count(distinct company) as "제조업체 수" from product;
--24
select ord_pno as "주문상품번호" ,sum(ord_cnt) as "총 주문수량" from orders group by ord_pno order by ord_pno asc; 
--25
select company as 제조업체, count(*) as 제품수, max(price) as 최고가 from product group by company;
--26
select company as 제조업체, count(*) as 제품수, max(price) as 최고가 from product group by company having count(*) >=2;
--27
select ord_pno, ord_cid,sum(ord_cnt) as "총 주문 수량" from orders GROUP BY ORD_PNO, ORD_CID ORDER BY ORD_PNO, ORD_CID;
--28
select ord_cid, pname from orders a join product b on a.ord_pno = b.pno where a.ord_cid = 'c102';
--29
select a.ord_cid,b.name,c.pname,a.ord_date from orders a join customer b on a.ord_cid = b.cid join product c on a.ord_pno = c.pno where trunc(a.ord_date) = to_date('2022-07-03','YYYY-MM-DD');

select * from orders;
select * from product;
select * from customer;